context:
  name: easydiffraction
  version: "0.21.1"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easydiffraction-${{ version }}.tar.gz
  sha256: 39ddb6b83f925cbfd4a97c34403cf0827a9c3ebd3f42ab20a3b96716cae4898f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - asciichartpy
    - pooch
    - typer
    - rich
    - varname
    - asteval
    - scipy
    - sympy
    - lmfit
    - bumps
    - emcee
    - dfo-ls
    - gemmi
    - cryspy >=0.12.1
    - crysfml >=0.8.0
    - diffpy.pdffit2
    - diffpy.utils
    - uncertainties
    - h5py
    - typeguard
    - darkdetect
    - pandas
    - plotly
    - pillow
    - pybaselines >=1.1

tests:
  - python:
      python_version:
        - ${{ python_min }}.*
        - "*"
      imports:
        - easydiffraction

about:
  homepage: https://github.com/easyscience/diffraction-lib/
  summary: Making diffraction data analysis and modelling easy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
    - conda-forge/easyscience
