context:
  name: easydiffraction
  version: "0.14.0"
  python_min: "3.12"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/easydiffraction-${{ version }}.tar.gz
  sha256: 661e94e13d8de4550955dac4f8650f2839e41e9a3f847365477104288073b1c6

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - versioningit
    - pip
  run:
    - python >=${{ python_min }}
    - essdiffraction
    - numpy
    - colorama
    - tabulate
    - asciichartpy
    - pooch
    - typer
    - rich
    - varname
    - asteval
    - scipy
    - sympy
    - lmfit
    - bumps
    - dfo-ls
    - gemmi
    - cryspy
    - diffpy.pdffit2
    - diffpy.utils
    - uncertainties
    - typeguard
    # visualization optional deps
    - darkdetect
    - pandas
    - py3Dmol
    - plotly

tests:
  - python:
      imports:
        - easydiffraction
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://easydiffraction.org/
  summary: Making diffraction data analysis and modelling easy
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - MridulS
